### ISSUE TITLE
Init project with one endpoint, docker, and postgresql db.

### ISSUE THREAD

**Issue by alxarno** [yasservice/social-core#1]
Create project. Use one docker container for your C# code and Postgresql DB. 
The application should process one REST endpoint for creating, get, delete, update user info (email, login, password, avatar).
Also, create a couple of tests for that issue.

**Comment by alxarno** [comment]
Branch - https://github.com/yasservice/social-core/tree/feature/1-project-init

**Comment by did-os** [comment]
Hi, @alxarno. Can u please create Docker?

**Comment by did-os** [comment]
@alxarno, check this commit.
